driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 1024
  network:
    # Allow access to the instance port; useful whilst troubleshooting
    - - forwarded_port
      - guest: 9080
        host: 9080
        auto_correct: true

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.6

suites:
  - name: default
    run_list: recipe[wlpdemo]
    attributes:
